#!/usr/bin/env python3
"""Run the local Script Matters consistency checks in a stable order."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def run(cmd: list[str], label: str | None = None) -> None:
    print("+ " + (label or " ".join(cmd)), flush=True)
    subprocess.run(cmd, cwd=ROOT, check=True)


def main() -> None:
    script_files = sorted(str(path.relative_to(ROOT)) for path in (ROOT / "scripts").glob("*.py"))
    checks = [
        ([sys.executable, "scripts/analyze_v5_bad_row_policy_sensitivity.py"], None),
        ([sys.executable, "scripts/build_v5_cross_script_diagnostics.py"], None),
        ([sys.executable, "scripts/analyze_v5_recoverability_sources.py"], None),
        ([sys.executable, "scripts/analyze_v5_cross_script_transfer.py"], None),
        ([sys.executable, "scripts/analyze_v5_review_label_sensitivity.py"], None),
        ([sys.executable, "scripts/analyze_v5_dataset_gap_intervals.py"], None),
        ([sys.executable, "scripts/analyze_v5_paired_sign_tests.py"], None),
        ([sys.executable, "scripts/analyze_v5_clustered_gap_robustness.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_subject_stability.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_subject_balance.py"], None),
        ([sys.executable, "scripts/build_v5_tokenization_failure_patterns.py"], None),
        ([sys.executable, "scripts/export_cross_script_agreement_examples.py"], None),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--outputs",
                "results/generated_views/phonetic_bangla_dev50_benqa_mcq_generated_bn.jsonl",
                "--target-views",
                "generated_bn",
                "--items-output",
                "results/analysis/phonetic_bangla_dev50_benqa_mcq_generated_bn_audit_items.csv",
                "--summary-output",
                "results/analysis/phonetic_bangla_dev50_benqa_mcq_generated_bn_audit_summary.csv",
                "--report-output",
                "reports/phonetic_bangla_generated_bn_dev50_benqa_mcq_audit.md",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--outputs",
                "results/generated_views/bnbphoneticparser_dev50_benqa_mcq_generated_bn.jsonl",
                "--target-views",
                "generated_bn",
                "--items-output",
                "results/analysis/bnbphoneticparser_dev50_benqa_mcq_generated_bn_audit_items.csv",
                "--summary-output",
                "results/analysis/bnbphoneticparser_dev50_benqa_mcq_generated_bn_audit_summary.csv",
                "--report-output",
                "reports/bnbphoneticparser_generated_bn_dev50_benqa_mcq_audit.md",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--outputs",
                "results/generated_views/phonetic_bangla_protected_dev50_benqa_mcq_generated_bn.jsonl",
                "--target-views",
                "generated_bn",
                "--items-output",
                "results/analysis/phonetic_bangla_protected_dev50_benqa_mcq_generated_bn_audit_items.csv",
                "--summary-output",
                "results/analysis/phonetic_bangla_protected_dev50_benqa_mcq_generated_bn_audit_summary.csv",
                "--report-output",
                "reports/phonetic_bangla_protected_generated_bn_dev50_benqa_mcq_audit.md",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--outputs",
                "results/generated_views/bnbphoneticparser_protected_dev50_benqa_mcq_generated_bn.jsonl",
                "--target-views",
                "generated_bn",
                "--items-output",
                "results/analysis/bnbphoneticparser_protected_dev50_benqa_mcq_generated_bn_audit_items.csv",
                "--summary-output",
                "results/analysis/bnbphoneticparser_protected_dev50_benqa_mcq_generated_bn_audit_summary.csv",
                "--report-output",
                "reports/bnbphoneticparser_protected_generated_bn_dev50_benqa_mcq_audit.md",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--outputs",
                "results/generated_views/phonetic_bangla_protected_v2_dev50_benqa_mcq_generated_bn.jsonl",
                "--target-views",
                "generated_bn",
                "--items-output",
                "results/analysis/phonetic_bangla_protected_v2_dev50_benqa_mcq_generated_bn_audit_items.csv",
                "--summary-output",
                "results/analysis/phonetic_bangla_protected_v2_dev50_benqa_mcq_generated_bn_audit_summary.csv",
                "--report-output",
                "reports/phonetic_bangla_protected_v2_generated_bn_dev50_benqa_mcq_audit.md",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--outputs",
                "results/generated_views/bnbphoneticparser_protected_v2_dev50_benqa_mcq_generated_bn.jsonl",
                "--target-views",
                "generated_bn",
                "--items-output",
                "results/analysis/bnbphoneticparser_protected_v2_dev50_benqa_mcq_generated_bn_audit_items.csv",
                "--summary-output",
                "results/analysis/bnbphoneticparser_protected_v2_dev50_benqa_mcq_generated_bn_audit_summary.csv",
                "--report-output",
                "reports/bnbphoneticparser_protected_v2_generated_bn_dev50_benqa_mcq_audit.md",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/build_generated_view_prompt_set.py",
                "--input",
                "data/slices/validation_200_v5.jsonl",
                "--id-source",
                "data/slices/validation_200_v4_dev50.jsonl",
                "--output",
                "data/generated_views/validation200_v5_dev50_benqa_mcq_generation_prompts.jsonl",
                "--report-output",
                "reports/generated_view_prompt_set_v5_dev50_benqa_mcq.md",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--prompts",
                "data/generated_views/validation200_v5_dev50_benqa_mcq_generation_prompts.jsonl",
                "--outputs",
                "results/generated_views/phonetic_bangla_protected_v2_v5_dev50_benqa_mcq_generated_bn.jsonl",
                "--target-views",
                "generated_bn",
                "--items-output",
                "results/analysis/phonetic_bangla_protected_v2_v5_dev50_benqa_mcq_generated_bn_audit_items.csv",
                "--summary-output",
                "results/analysis/phonetic_bangla_protected_v2_v5_dev50_benqa_mcq_generated_bn_audit_summary.csv",
                "--report-output",
                "reports/phonetic_bangla_protected_v2_v5_generated_bn_dev50_benqa_mcq_audit.md",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--prompts",
                "data/generated_views/validation200_v5_dev50_benqa_mcq_generation_prompts.jsonl",
                "--outputs",
                "results/generated_views/bnbphoneticparser_protected_v2_v5_dev50_benqa_mcq_generated_bn.jsonl",
                "--target-views",
                "generated_bn",
                "--items-output",
                "results/analysis/bnbphoneticparser_protected_v2_v5_dev50_benqa_mcq_generated_bn_audit_items.csv",
                "--summary-output",
                "results/analysis/bnbphoneticparser_protected_v2_v5_dev50_benqa_mcq_generated_bn_audit_summary.csv",
                "--report-output",
                "reports/bnbphoneticparser_protected_v2_v5_generated_bn_dev50_benqa_mcq_audit.md",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/build_generated_bn_answer_audit_slice.py",
                "--items",
                "data/slices/validation_200_v5.jsonl",
                "--output",
                "data/generated_views/validation200_v5_dev50_benqa_mcq_protected_v2_generated_bn_answer_audit.jsonl",
                "--report-output",
                "reports/generated_bn_answer_audit_slice_v5_dev50_benqa_mcq.md",
                "--status",
                "reviewed_v5_protected_v2_deterministic_generated_bn_dev_audit",
                "--generator-spec",
                "generated_bn_phonetic_protected_v2=results/generated_views/phonetic_bangla_protected_v2_v5_dev50_benqa_mcq_generated_bn.jsonl",
                "--generator-spec",
                "generated_bn_bnb_protected_v2=results/generated_views/bnbphoneticparser_protected_v2_v5_dev50_benqa_mcq_generated_bn.jsonl",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--prompts",
                "data/generated_views/validation200_v5_dev50_benqa_mcq_generation_prompts.jsonl",
                "--outputs",
                "results/generated_views/phonetic_bangla_protected_v3_v5_dev50_benqa_mcq_generated_bn.jsonl",
                "--target-views",
                "generated_bn",
                "--items-output",
                "results/analysis/phonetic_bangla_protected_v3_v5_dev50_benqa_mcq_generated_bn_audit_items.csv",
                "--summary-output",
                "results/analysis/phonetic_bangla_protected_v3_v5_dev50_benqa_mcq_generated_bn_audit_summary.csv",
                "--report-output",
                "reports/phonetic_bangla_protected_v3_v5_generated_bn_dev50_benqa_mcq_audit.md",
                "--fail-on-hard-fail",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--prompts",
                "data/generated_views/validation200_v5_dev50_benqa_mcq_generation_prompts.jsonl",
                "--outputs",
                "results/generated_views/bnbphoneticparser_protected_v3_v5_dev50_benqa_mcq_generated_bn.jsonl",
                "--target-views",
                "generated_bn",
                "--items-output",
                "results/analysis/bnbphoneticparser_protected_v3_v5_dev50_benqa_mcq_generated_bn_audit_items.csv",
                "--summary-output",
                "results/analysis/bnbphoneticparser_protected_v3_v5_dev50_benqa_mcq_generated_bn_audit_summary.csv",
                "--report-output",
                "reports/bnbphoneticparser_protected_v3_v5_generated_bn_dev50_benqa_mcq_audit.md",
                "--fail-on-hard-fail",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/build_generated_bn_answer_audit_slice.py",
                "--items",
                "data/slices/validation_200_v5.jsonl",
                "--output",
                "data/generated_views/validation200_v5_dev50_benqa_mcq_protected_v3_generated_bn_answer_audit.jsonl",
                "--report-output",
                "reports/generated_bn_answer_audit_slice_v5_dev50_benqa_mcq_protected_v3.md",
                "--status",
                "reviewed_v5_protected_v3_formulaish_deterministic_generated_bn_dev_audit",
                "--generator-spec",
                "generated_bn_phonetic_protected_v3=results/generated_views/phonetic_bangla_protected_v3_v5_dev50_benqa_mcq_generated_bn.jsonl",
                "--generator-spec",
                "generated_bn_bnb_protected_v3=results/generated_views/bnbphoneticparser_protected_v3_v5_dev50_benqa_mcq_generated_bn.jsonl",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--outputs",
                "results/generated_views/qwen3_4b_selftranslate_generated_en_dev50_benqa_mcq.jsonl",
                "--target-views",
                "generated_en",
                "--items-output",
                "results/analysis/qwen3_4b_selftranslate_generated_en_dev50_benqa_mcq_audit_items.csv",
                "--summary-output",
                "results/analysis/qwen3_4b_selftranslate_generated_en_dev50_benqa_mcq_audit_summary.csv",
                "--report-output",
                "reports/qwen3_4b_selftranslate_generated_en_dev50_benqa_mcq_audit.md",
            ],
            None,
        ),
        ([sys.executable, "scripts/repair_generated_en_outputs.py"], None),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--prompts",
                "data/generated_views/validation200_v5_dev50_benqa_mcq_generation_prompts.jsonl",
                "--outputs",
                "results/generated_views/qwen3_4b_selftranslate_guarded_v5_dev50_benqa_mcq_generated_en.jsonl",
                "--target-views",
                "generated_en",
                "--items-output",
                "results/analysis/qwen3_4b_selftranslate_guarded_v5_dev50_benqa_mcq_generated_en_audit_items.csv",
                "--summary-output",
                "results/analysis/qwen3_4b_selftranslate_guarded_v5_dev50_benqa_mcq_generated_en_audit_summary.csv",
                "--report-output",
                "reports/qwen3_4b_selftranslate_guarded_v5_generated_en_dev50_benqa_mcq_audit.md",
                "--fail-on-hard-fail",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/build_generated_view_answer_audit_slice.py",
                "--items",
                "data/slices/validation_200_v5.jsonl",
                "--output",
                "data/generated_views/validation200_v5_dev50_benqa_mcq_guarded_generated_en_answer_audit.jsonl",
                "--report-output",
                "reports/generated_view_answer_audit_slice_v5_dev50_benqa_mcq_guarded_en.md",
                "--status",
                "reviewed_v5_qwen3_guarded_generated_en_dev_audit",
                "--title",
                "Guarded Generated-EN Answer Audit Slice: Dev50 BEnQA MCQ",
                "--generator-spec",
                "generated_en_qwen3_guarded=results/generated_views/qwen3_4b_selftranslate_guarded_v5_dev50_benqa_mcq_generated_en.jsonl",
            ],
            None,
        ),
        ([sys.executable, "scripts/analyze_generated_view_agreement_route_dev.py"], None),
        (
            [
                sys.executable,
                "scripts/analyze_generated_view_agreement_route_dev.py",
                "--items",
                "data/generated_views/validation200_v5_dev50_benqa_mcq_protected_v3_generated_bn_answer_audit.jsonl",
                "--bn-eval",
                "results/runs/qwen3_4b_generated_bn_v5_pv3_dev50/results/runs/qwen3_4b_generated_bn_v5_pv3_dev50.jsonl",
                "--en-eval",
                "results/runs/qwen3_4b_guarded_generated_en_v5_dev50/results/runs/qwen3_4b_guarded_generated_en_v5_dev50.jsonl",
                "--items-output",
                "results/analysis/qwen3_4b_pv3_bn_guarded_en_agreement_route_dev_items.csv",
                "--summary-output",
                "results/analysis/qwen3_4b_pv3_bn_guarded_en_agreement_route_dev_summary.csv",
                "--report-output",
                "reports/qwen3_4b_pv3_bn_guarded_en_agreement_route_dev.md",
                "--en-audit-items",
                "results/analysis/qwen3_4b_selftranslate_guarded_v5_dev50_benqa_mcq_generated_en_audit_items.csv",
                "--bn-variant",
                "generated_bn_bnb_protected_v3",
                "--en-variant",
                "generated_en_qwen3_guarded",
                "--bn-label",
                "Protected-v3 BNB generated-BN",
                "--en-label",
                "Guarded generated-English",
                "--report-title",
                "Qwen3-4B Protected-v3 BN + Guarded-EN Agreement Route: Dev",
                "--decision-note",
                "This route uses reviewed-v5 protected-v3 generated-BN plus guarded generated-English. The guarded English view passes hard preservation, but source fallbacks make this dev-only mitigation evidence.",
                "--rescore",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/analyze_generated_view_agreement_route_dev.py",
                "--items",
                "data/generated_views/validation200_v5_dev50_benqa_mcq_protected_v3_generated_bn_answer_audit.jsonl",
                "--bn-eval",
                "results/runs/qwen25_3b_generated_bn_v5_pv3_dev50/results/runs/qwen25_3b_generated_bn_v5_pv3_dev50.jsonl",
                "--en-eval",
                "results/runs/qwen25_3b_guarded_generated_en_v5_dev50/results/runs/qwen25_3b_guarded_generated_en_v5_dev50.jsonl",
                "--items-output",
                "results/analysis/qwen25_3b_pv3_bn_guarded_en_agreement_route_dev_items.csv",
                "--summary-output",
                "results/analysis/qwen25_3b_pv3_bn_guarded_en_agreement_route_dev_summary.csv",
                "--report-output",
                "reports/qwen25_3b_pv3_bn_guarded_en_agreement_route_dev.md",
                "--en-audit-items",
                "results/analysis/qwen3_4b_selftranslate_guarded_v5_dev50_benqa_mcq_generated_en_audit_items.csv",
                "--bn-variant",
                "generated_bn_phonetic_protected_v3",
                "--en-variant",
                "generated_en_qwen3_guarded",
                "--bn-label",
                "Protected-v3 phonetic generated-BN",
                "--en-label",
                "Guarded generated-English",
                "--report-title",
                "Qwen2.5-3B Protected-v3 BN + Guarded-EN Agreement Route: Dev",
                "--decision-note",
                "This route uses reviewed-v5 protected-v3 generated-BN plus guarded generated-English. It is negative on dev and should not be launched on test150.",
                "--rescore",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/audit_generated_view_outputs.py",
                "--outputs",
                "results/generated_views/fms_byte_protected_dev50_benqa_mcq_generated_bn.jsonl",
                "--target-views",
                "generated_bn",
                "--items-output",
                "results/analysis/fms_byte_protected_dev50_benqa_mcq_generated_bn_audit_items.csv",
                "--summary-output",
                "results/analysis/fms_byte_protected_dev50_benqa_mcq_generated_bn_audit_summary.csv",
                "--report-output",
                "reports/fms_byte_protected_generated_bn_dev50_benqa_mcq_audit.md",
            ],
            None,
        ),
        ([sys.executable, "scripts/analyze_generated_bn_reference_similarity.py"], None),
        ([sys.executable, "scripts/analyze_guarded_generated_en_provenance.py"], None),
        ([sys.executable, "scripts/analyze_generated_view_route_bottleneck.py"], None),
        ([sys.executable, "scripts/analyze_generated_view_routing_candidates.py"], None),
        ([sys.executable, "scripts/analyze_v5_banglish_fragility_features.py"], None),
        ([sys.executable, "scripts/analyze_v5_qwen_scaling_transfer.py"], None),
        ([sys.executable, "scripts/analyze_v5_fragility_model_overlap.py"], None),
        ([sys.executable, "scripts/analyze_v5_item_consensus.py"], None),
        ([sys.executable, "scripts/analyze_v5_difficulty_conditioned_gap.py"], None),
        ([sys.executable, "scripts/analyze_v5_consensus_stability.py"], None),
        ([sys.executable, "scripts/analyze_v5_composition_sensitivity.py"], None),
        ([sys.executable, "scripts/export_v5_shared_fragility_examples.py"], None),
        ([sys.executable, "scripts/build_v5_subject_breakdown.py"], None),
        ([sys.executable, "scripts/analyze_v5_answer_format_audit.py"], None),
        ([sys.executable, "scripts/analyze_v5_response_style_drift.py"], None),
        ([sys.executable, "scripts/analyze_v5_banglamath_numeric_sensitivity.py"], None),
        ([sys.executable, "scripts/analyze_v5_banglamath_numeric_transfer.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_choice_bias.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_subject_option_bias.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_prediction_diversity.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_option_position_content.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_option_switching.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_cross_script_option_agreement.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_cross_model_banglish_agreement.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_order_confound.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_review_label_option_bias.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_length_token_confound.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_option_coverage_confound.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_option_switch_confound.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_option_semantic_cues.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_multiconfound_residual.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_distractor_transition.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_label_balance.py"], None),
        ([sys.executable, "scripts/build_v5_benqa_option_permutation_probe.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_option_permutation_probe.py"], None),
        ([sys.executable, "scripts/build_bnsentmix_external_validation_slice.py"], None),
        ([sys.executable, "scripts/analyze_bnsentmix_external_validation.py"], None),
        ([sys.executable, "scripts/analyze_bnsentmix_model_complementarity.py"], None),
        ([sys.executable, "scripts/analyze_bnsentmix_routing_devtest.py"], None),
        (
            [
                sys.executable,
                "scripts/compare_banglish_distributions.py",
                "--validation",
                "data/slices/validation_200_v5.jsonl",
                "--validation-variant",
                "banglish_clean",
                "--banglatlit",
                "literature/code/BanglaTLit/data/BanglaTLiT_val.csv",
                "literature/code/BanglaTLit/data/BanglaTLiT_test.csv",
                "--items-output",
                "results/analysis/banglatlit_vs_validation200_v5_banglish_distribution_items.csv",
                "--summary-output",
                "results/analysis/banglatlit_vs_validation200_v5_banglish_distribution_summary.csv",
                "--top-words-output",
                "results/analysis/banglatlit_vs_validation200_v5_banglish_top_words.csv",
            ],
            None,
        ),
        (
            [
                sys.executable,
                "scripts/analyze_banglatlit_spelling_variation.py",
                "--banglatlit",
                "literature/code/BanglaTLit/data/BanglaTLiT_val.csv",
                "literature/code/BanglaTLit/data/BanglaTLiT_test.csv",
                "--summary-output",
                "results/analysis/banglatlit_spelling_variation_summary.csv",
                "--variation-output",
                "results/analysis/banglatlit_spelling_variation_tokens.csv",
            ],
            None,
        ),
        ([sys.executable, "scripts/analyze_v5_banglatlit_lexical_coverage.py"], None),
        ([sys.executable, "scripts/analyze_v5_benqa_option_lexical_coverage.py"], None),
        ([sys.executable, "scripts/analyze_v5_banglatlit_model_coverage_sensitivity.py"], None),
        ([sys.executable, "scripts/analyze_v5_banglatlit_spelling_variation_sensitivity.py"], None),
        ([sys.executable, "scripts/analyze_v5_source_variant_structural_parity.py"], None),
        ([sys.executable, "scripts/analyze_v5_english_warning_sensitivity.py"], None),
        ([sys.executable, "scripts/analyze_v5_review_edit_distance_sensitivity.py"], None),
        ([sys.executable, "scripts/check_research_log_compactness.py"], None),
        ([sys.executable, "scripts/build_thesis_tables.py"], None),
        ([sys.executable, "scripts/check_thesis_tables.py"], None),
        ([sys.executable, "scripts/build_thesis_figures.py"], None),
        ([sys.executable, "scripts/check_thesis_figures.py"], None),
        ([sys.executable, "scripts/compile_thesis_draft.py"], None),
        ([sys.executable, "scripts/export_v5_substitution_review_playbook.py"], None),
        ([sys.executable, "scripts/plan_v5_review_sessions.py"], None),
        ([sys.executable, "scripts/export_v5_review_session_packets.py"], None),
        ([sys.executable, "scripts/export_v5_review_resume_card.py"], None),
        ([sys.executable, "scripts/build_v5_next_session_brief.py"], None),
        ([sys.executable, "scripts/check_v5_review_packet_integrity.py"], None),
        ([sys.executable, "scripts/summarize_v5_review_progress.py"], None),
        ([sys.executable, "scripts/validate_banglish_review_queue.py"], None),
        ([sys.executable, "scripts/check_post_v5_rerun_readiness.py"], None),
        ([sys.executable, "scripts/build_post_v5_kaggle_job_plan.py"], None),
        ([sys.executable, "scripts/build_post_v5_compute_budget.py"], None),
        ([sys.executable, "scripts/build_api_audit_smoke_subset.py"], None),
        ([sys.executable, "scripts/estimate_prompt_budget.py"], None),
        (
            [
                sys.executable,
                "scripts/estimate_prompt_budget.py",
                "--input",
                "data/slices/api_audit_smoke_10_v5.jsonl",
                "--output",
                "results/analysis/api_audit_smoke_10_v5_prompt_budget_summary.csv",
                "--report",
                "reports/api_audit_smoke_10_v5_prompt_budget.md",
            ],
            None,
        ),
        ([sys.executable, "scripts/build_api_audit_prompt_manifest.py"], None),
        ([sys.executable, "scripts/check_api_audit_manifest.py"], None),
        ([sys.executable, "scripts/check_api_audit_import_roundtrip.py"], None),
        ([sys.executable, "scripts/check_literature_corpus.py"], None),
        ([sys.executable, "scripts/check_citation_readiness.py"], None),
        ([sys.executable, "scripts/check_secret_hygiene.py"], None),
        ([sys.executable, "scripts/check_local_artifact_refs.py"], None),
        (
            [sys.executable, "-m", "py_compile", *script_files],
            f"{sys.executable} -m py_compile scripts/*.py",
        ),
        ([sys.executable, "scripts/build_current_research_status_dashboard.py"], None),
        ([sys.executable, "scripts/build_artifact_manifest.py"], None),
    ]
    for cmd, label in checks:
        run(cmd, label)
    print("all local research checks passed")


if __name__ == "__main__":
    main()
